version: '2'
services:
  server:
    image: "jetbrains/teamcity-server:2017.2.2"
    ports:
    - "8111:8111"
    volumes:
    - ./data/server/data:/data/teamcity_server/datadir
    - ./data/server/logs:/opt/teamcity/logs
  agent:
    build:
      context: .
      dockerfile: Dockerfile-agent
    volumes:
    - ./data/agent/conf:/data/teamcity_agent/conf
    - /opt/buildagent/work:/opt/buildagent/work
    - /opt/buildagent/temp:/opt/buildagent/temp
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - AGENT_NAME=AgentSmith
    - SERVER_URL=http://server:8111/
    links:
    - server
    - registry
  registry:
    image: "registry:2"
    ports:
    - "5000:5000"
    volumes:
    - ./data/registry:/var/lib/registry
    - ./data/certs:/certs
    environment:
    - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.local.crt
    - REGISTRY_HTTP_TLS_KEY=/certs/registry.local.key
