apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          imagePullPolicy: IfNotPresent
          ports:
            - name: jenkins
              containerPort: 8080
              hostPort: 8080
          livenessProbe:
            tcpSocket:
              port: jenkins
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: jenkins
            initialDelaySeconds: 90
            periodSeconds: 10
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
      volumes:
        - name: jenkins-home
          hostPath:
            path: /var/jenkins_home # needs chown 1000:1000 inside minikube
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
    - name: jenkins
      protocol: TCP
      port: 8080
      nodePort: 30300
  selector:
    app: jenkins
  type: NodePort
