apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teamcity-server
  labels:
    app: teamcity-server
spec:
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
        - name: teamcity-server
          image: jetbrains/teamcity-server:2018.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: teamcity-server
              containerPort: 8111
              hostPort: 8111
          livenessProbe:
            tcpSocket:
              port: teamcity-server
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: teamcity-server
            initialDelaySeconds: 90
            periodSeconds: 10
          volumeMounts:
            - mountPath: /data/teamcity_server/datadir
              name: data
      volumes:
        - name: data
          hostPath:
            path: /c/Users/ngeor/Projects/github/blog-helm/teamcity-server/data/server/datadir
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
spec:
  ports:
    - name: teamcity-server
      protocol: TCP
      port: 8111
      nodePort: 30200
  selector:
    app: teamcity-server
  type: NodePort
