apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teamcity-server
  labels:
    app: teamcity-server
spec:
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
        - name: teamcity-server
          image: jetbrains/teamcity-server:2017.2.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: teamcity-server
              containerPort: 8111
              hostPort: 8111
          livenessProbe:
            tcpSocket:
              port: teamcity-server
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: teamcity-server
            initialDelaySeconds: 120
            periodSeconds: 10
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teamcity-agent
  labels:
    app: teamcity-agent
spec:
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
      containers:
        - name: teamcity-agent
          image: jetbrains/teamcity-agent:2017.2.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: teamcity-agent
              containerPort: 9090
              hostPort: 9090
          env:
            - name: AGENT_NAME
              value: TeamCityKubeAgent
            - name: SERVER_URL
              value: http://teamcity-server:8111/
          livenessProbe:
            tcpSocket:
              port: teamcity-agent
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: teamcity-agent
            initialDelaySeconds: 120
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
spec:
  ports:
    - name: teamcity-server
      protocol: TCP
      port: 8111
      nodePort: 30200
  selector:
    app: teamcity-server
  type: NodePort
