# Opens a NodePort for Tiller, so it's possible to reach it at port 30200 on the local IP.
kind: Service
apiVersion: v1
metadata:
  name: tiller-nodeport
  namespace: kube-system
spec:
  ports:
    - name: tiller
      protocol: TCP
      port: 44134
      nodePort: 30200
      targetPort: tiller
  selector:
    app: helm
    name: tiller
  type: NodePort
