apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - name: registry
              containerPort: 5000
              hostPort: 5000
          livenessProbe:
            tcpSocket:
              port: registry
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: registry
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: /certs
              name: registry-certs
            - mountPath: /var/lib/registry
              name: registry-data
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/registry.default.svc.cluster.local.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/registry.default.svc.cluster.local.key
      volumes:
        - name: registry-certs
          hostPath:
            path: /certs
        - name: registry-data
          hostPath:
            path: /vagrant/data/registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  ports:
    - name: registry
      protocol: TCP
      port: 5000
      nodePort: 30400
  selector:
    app: registry
  type: NodePort
